spring.application.name=FitnessApp

# ===============================
# DATABASE CONFIG (Neon PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-tiny-art-amnetp2i-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_R2f1PTaMCiAB

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=8080